# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BIOL2002 Lab Notes
email: dnedveck@umn.edu
description: > # this means to ignore newlines until "baseurl:"
  Blog posts from the lab, along with pages of resources -- nice.

baseurl: "/biol2002" # the subpath of your site, e.g. /blog
url: "http://dnedveck.github.io" # the base hostname & protocol for your site

twitter_username: dnedveck
github_username:  dnedveck

# Build settings
markdown: kramdown
# include: [staticdocs, assets]
